### ISSUE TITLE
Drill down into Dictionaries

### ISSUE THREAD

**Issue by jfheins** [maranmaran/dotnet-differ#14]
I like the project but I encountered an issue: When I have an object that has a Dictionary property, the whole dictionary is considered changes.

When the collection is an array, I get a path like "vehicles.0.name" that changed, but with Dictionary it's always "vehicles.0" and a large value.

I think this would be a simple test case:
```
public class DictionaryOfComplexType
{
    public Dictionary<string, ComplexType> Data { get; set; } = new();
}


[Fact]
public void DictionaryProperty_IsResolved()
{
    var faker = new AutoFaker<ComplexType>();
    var left = new DictionaryOfComplexType
    {
        Data = { ["key"] = faker.UseSeed(1).Generate() }
    };
    var right = new DictionaryOfComplexType
    {
        Data = { ["key"] = faker.UseSeed(2).Generate() }
    };

    var diff = DifferDotNet.Diff(left, right).Single();

    Assert.Equal("data.key.string", diff.FullPath);
    // or like this
    Assert.Equal("data['key'].string", diff.FullPath);
    
    Assert.Equal(left.Data["key"].String, diff.LeftValue);
    Assert.Equal(right.Data["key"].String, diff.RightValue);
}
```

My anticipated use case uses Guid as key but I could use strings as well.

Side note: The iteration order of Dictionaries is not well defined, so ideally a dictionary diff should never reference elements by index.

**Comment by maranmaran** [comment]
Yeah I agree, I forgot a little bit on why I've made that initial decision. But I don't see a reason why we couldn't drill in. 

I belive whenever I had similar use-case. Since I've only ever used it for lightweight diffing on change tracking for some auditing purposes I would have specialized dto's for diffs. 

Where then I would translate from entities into these DTO's to diff them. 
There you could morph it into something other than dict avoiding complexity and/or having a workaround for yourself if you rely on this. 

Till then I've started some work here https://github.com/maranmaran/dotnet-differ/pull/15
